# Generated by Django 4.0.5 on 2022-06-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('channel_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='kanal ismi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
