# Generated by Django 4.0.5 on 2022-06-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_name_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
