# Generated by Django 4.0.5 on 2022-06-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='text@text.com', max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
