# Generated by Django 4.0.5 on 2022-06-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
