# Generated by Django 4.0.5 on 2022-06-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_date_joined_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taks_id', models.CharField(max_length=100, verbose_name='Görev ID')),
                ('status', models.CharField(choices=[('ONP', 'On Progress'), ('FNS', 'Finished')], default='ONP', max_length=3, verbose_name='Görev Durumu')),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='Görev Başlama Zamanı')),
            ],
        ),
    ]
