version: "3.3"

services:
  redis:
    image: redis

  web:
    restart: always
    image: app
    volumes:
      - .:/code
    # command:  gunicorn redis_tutorial.wsgi:application --bind 0.0.0.0:8000
    command:  ./docker-entrypoint.sh
    expose:
      - 8000
    depends_on:
      - rq

    environment:
      - AWS_ACCESS_KEY_ID=AKIARAXQ2NHKJU6EGZ4S
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_STORAGE_BUCKET_NAME=redis-django
  rq:
    build: .
    image: app
    command: python manage.py rqworker
    volumes:
      - .:/code
    depends_on:
      - redis

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
