# Generated by Django 4.0.5 on 2022-06-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='İsim')),
                ('last_name', models.CharField(max_length=30, verbose_name='Soy İsim')),
                ('channel_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='kanal ismi')),
            ],
        ),
    ]
